"""empty message

Revision ID: 01edf691a8cc
Revises: a59681265bc1
Create Date: 2021-02-10 22:09:03.275016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01edf691a8cc'
down_revision = 'a59681265bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pads', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pads', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pads', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pads', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
