"""empty message

Revision ID: a74ea08413ec
Revises: 44a330fa5d21
Create Date: 2021-02-10 11:19:01.507881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a74ea08413ec'
down_revision = '44a330fa5d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pad_list', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('block_seq', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('note_seq', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('beats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('beat_col', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('beat_row', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='beats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='beats_pkey')
    )
    op.drop_table('pads')
    op.drop_table('boards')
    # ### end Alembic commands ###
