"""empty message

Revision ID: 44a330fa5d21
Revises: 
Create Date: 2021-02-08 16:14:15.407895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44a330fa5d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('beat_col', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('beats', sa.Column('beat_row', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('beats', 'beat_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('beat_data', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('beats', 'beat_row')
    op.drop_column('beats', 'beat_col')
    # ### end Alembic commands ###
